//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneradorLlavesRSA.Web
{
    public partial class DemoRSA
    {
        protected global::System.Web.UI.WebControls.Panel AccessDeniedPanel;
        protected global::System.Web.UI.WebControls.Panel RsaPanel;
        protected global::System.Web.UI.HtmlControls.HtmlForm RsaForm;
        protected global::System.Web.UI.WebControls.HiddenField PublicKeyDerField;
        protected global::System.Web.UI.WebControls.HiddenField CiphertextField;
        protected global::System.Web.UI.WebControls.Literal FingerprintLiteral;
        protected global::System.Web.UI.WebControls.Button SubmitCipherButton;
        protected global::System.Web.UI.WebControls.Panel ServerMessagePanel;
        protected global::System.Web.UI.WebControls.Literal ServerMessageLiteral;
        protected global::System.Web.UI.WebControls.Panel ResultPanel;
        protected global::System.Web.UI.WebControls.Literal DecryptedLiteral;
    }
}
